spring:
  application:
    name:  hotels
  main:
    banner-mode: console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
   level:
      ROOT: INFO
      com.scalors.hotels.marryat: DEBUG



